### ISSUE TITLE
Extension fails to build

### ISSUE THREAD

**Issue by zats** [raycast/extensions-swift-sample#1]
Hey folks, just getting started and running into the issue following the readme.

Imported extensions successfully (seeing the commands in raycast)
Trying to build the extension running into following issue:

```
$ cd "/tmp/extensions-swift-sample" && npm run dev

> dev
> ray develop

info  -  entry points [src/noArgumentsNoReturn.tsx src/multipleArguments.tsx src/arrayArguments.tsx src/delayedExecution.tsx src/returnClass.tsx src/errorAsString.tsx src/errorAsEnum.tsx src/optionals.tsx]
error -  compiling swift package
build failed (src/optionals.tsx:3:26 import { optionals } from "swift:../swift";): Cannot find Swift sources directory: ../../private/tmp/extensions-swift-sample/swift/Sources
```

is there an additional step I am missing? (the folder referenced in the error message is actually present on the disk, tho not 100% sure about the relative path tbf)

**Update**: checking out again and running
```
$ npm install
$ npm run dev

> dev
> ray develop

info  -  entry points [src/noArgumentsNoReturn.tsx src/multipleArguments.tsx src/arrayArguments.tsx src/delayedExecution.tsx src/returnClass.tsx src/errorAsString.tsx src/errorAsEnum.tsx src/optionals.tsx]
error -  compiling swift package
build failed (src/delayedExecution.tsx:3:32 import { delayedGreeting } from "swift:../swift";): Cannot find Swift sources directory: ../../private/tmp/extensions-swift-sample/swift/Sources
```

~worked, will re-open the issue if I see it again~

**Comment by Visual-Studio-Coder** [comment]
Am getting the same error.

**Comment by filiptepper** [comment]
Getting a different one.

```
npm run build

> build
> ray build -e dist

info  - entry points ["src/noArgumentsNoReturn.tsx","src/multipleArguments.tsx","src/arrayArguments.tsx","src/delayedExecution.tsx","src/returnClass.tsx","src/errorAsString.tsx","src/errorAsEnum.tsx","src/optionals.tsx"]
ready  - compiling swift package
    Error: Build failed with 1 error:
    node_modules/esbuild/lib/main.js:254:12: ERROR: [plugin: swift-files] Invalid option from onLoad() callback in plugin "swift-files": "Contents"
```

**Comment by Visual-Studio-Coder** [comment]
Yes, am getting exact same thing. I said "getting same error" after trying it on a lower version. Funny... hope this gets resolved.

**Comment by omarshahine** [comment]
Same. Hope this gets fixed as I need to use this.

**Comment by Visual-Studio-Coder** [comment]
You guys should check out this issue I created:
https://github.com/raycast/extensions-swift-tools/issues/7

It's the more recent issue that we're facing. They said they'd fix it last week, but they didn't 😭. My extension's PR has been sitting there for a month.

Also for some reason, the extension compiles properly during the raycast bot checks, but it doesn't when I do it locally...

**Comment by mathieudutour** [comment]
Fixed in 1.96.1

**Comment by omarshahine** [comment]
> Fixed in 1.96.1

omarshahine@Mac extensions-swift-sample-main % npm list @raycast/api
extensions-swift-sample@ /Users/omarshahine/Downloads/extensions-swift-sample-main
├── @raycast/api@1.96.1
└─┬ @raycast/utils@1.19.1
  └── @raycast/api@1.96.1 deduped

omarshahine@Mac extensions-swift-sample-main % ray build    
info  - entry points ["src/noArgumentsNoReturn.tsx","src/multipleArguments.tsx","src/arrayArguments.tsx","src/delayedExecution.tsx","src/returnClass.tsx","src/errorAsString.tsx","src/errorAsEnum.tsx","src/optionals.tsx","src/searchContacts.tsx","src/simpleContacts.tsx"]
error  - compiling swift package
failed to compile swift: ** INTERNAL ERROR: Unable to load workspace '/Users/omarshahine/Downloads/extensions-swift-sample-main/swift' **
Uncaught Exception: -[Swift.__SwiftDeferredNSArray intersectsSet:]: unrecognized selector sent to instance 0x1190e7210
Stack:
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   -[NSObject(NSObject) __retain_OA] (in CoreFoundation)
  3   ___forwarding___ (in CoreFoundation)
  4   _CF_forwarding_prep_0 (in CoreFoundation)
  5   -[DVTCoreDevice(DVTCoreDeviceIDE) deviceSupportsBuildable:buildParameters:error:] (in IDEFoundation)
  6   -[DVTCoreDevice(DVTCoreDeviceIDE) supportedArchitecturesForBuildableContext:buildParameters:error:] (in IDEFoundation)
  7   _IDERunDestinationsForBuildableUsingDeviceWithBuildParameters (in IDEFoundation)
  8   -[IDERunDestinationManager runDestinationsForScheme:schemeCommands:executionEnvironment:eligibleOnly:genericOnly:architectureVisibility:] (in IDEFoundation)
  9   IDESchemeDetermineAvailableRunDestinations (in IDEFoundation)
 10   -[IDEScheme _actuallyInvalidateAvailableRunDestinations] (in IDEFoundation)
 11   addSchemeAndMakeActiveIfNecessary #1 (result:error:) in IDESwiftPackage.generateScheme(with:buildable:additionalBuildables:unsetRunnable:makeActive:orderHint:) (in IDESwiftPackageCore)
 12   IDESwiftPackage.generateScheme(with:buildable:additionalBuildables:unsetRunnable:makeActive:orderHint:) (in IDESwiftPackageCore)
 13   IDESwiftPackage.generateSchemes(_:isRootPackage:) (in IDESwiftPackageCore)
 14   IDESwiftPackage.update(from:graphHasErrors:delegate:) (in IDESwiftPackageCore)
 15   specialized IDESPMWorkspaceDelegate.rootPackagesDidUpdate(packages:graphHasErrors:modelGraphSynchronizerToken:) (in IDESwiftPackageCore)
 16   closure #1 in IDESPMWorkspaceDelegate.packageGraphDidFinishAction(_:duration:result:) (in IDESwiftPackageCore)
 17   partial apply for closure #1 in IDESPMWorkspaceDelegate.disableWorkspaceContentSynchronization(during:) (in IDESwiftPackageCore)
 18   <deduplicated_symbol> (in DVTFoundation)
 19   <deduplicated_symbol> (in DVTFoundation)
 20   thunk for @escaping @callee_guaranteed () -> () (in DVTFoundation)
 21   __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
 22   -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
 23   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
 24   DVTModelObjectGraph.performBlockCoalescingModelChanges<A>(_:) (in DVTFoundation)
 25   IDESPMWorkspaceDelegate.disableWorkspaceContentSynchronization(during:) (in IDESwiftPackageCore)
 26   IDESPMWorkspaceDelegate.packageGraphDidFinishAction(_:duration:result:) (in IDESwiftPackageCore)
 27   <deduplicated_symbol> (in IDESwiftPackageCore)
 28   SPMWorkspace.packageGraphActionFinished(_:) (in SwiftPM)
 29   closure #2 in closure #3 in SPMWorkspace.processPackageGraphActionsInBackgroundIfNeeded(canProcessPackageGraphActions:) (in SwiftPM)
 30   <deduplicated_symbol> (in SwiftPM)
 31   <deduplicated_symbol> (in SwiftPM)
 32   <deduplicated_symbol> (in SwiftPM)
 33   completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) (in libswift_Concurrency.dylib)


You can try to delete the /Users/omarshahine/Downloads/extensions-swift-sample-main/swift/.raycast-swift-build folder and run this command again, sometimes it helps
    Error: Build failed with 1 error:
    src/errorAsString.tsx:3:38: ERROR: [plugin: swift-files] failed to import Swift package from 
    "/Users/omarshahine/Downloads/extensions-swift-sample-main/swift". Make sure you reference the folder that includes the 
    'Package.swift' file
omarshahine@Mac extensions-swift-sample-main %

**Comment by omarshahine** [comment]
> 1.96.1

So I updated my NPM packages and package.json and still cannot build

omarshahine@Mac extensions-swift-sample-main % npm list @raycast/api    
extensions-swift-sample@ /Users/omarshahine/Downloads/extensions-swift-sample-main
├── @raycast/api@1.96.1
└─┬ @raycast/utils@1.19.1
  └── @raycast/api@1.96.1 deduped

omarshahine@Mac extensions-swift-sample-main % ray build
info  - entry points ["src/noArgumentsNoReturn.tsx","src/multipleArguments.tsx","src/arrayArguments.tsx","src/delayedExecution.tsx","src/returnClass.tsx","src/errorAsString.tsx","src/errorAsEnum.tsx","src/optionals.tsx","src/searchContacts.tsx","src/simpleContacts.tsx"]
error  - compiling swift package
failed to compile swift: ** INTERNAL ERROR: Unable to load workspace '/Users/omarshahine/Downloads/extensions-swift-sample-main/swift' **
Uncaught Exception: -[Swift.__SwiftDeferredNSArray intersectsSet:]: unrecognized selector sent to instance 0x113384ca0
Stack:
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   -[NSObject(NSObject) __retain_OA] (in CoreFoundation)
  3   ___forwarding___ (in CoreFoundation)
  4   _CF_forwarding_prep_0 (in CoreFoundation)
  5   -[DVTCoreDevice(DVTCoreDeviceIDE) deviceSupportsBuildable:buildParameters:error:] (in IDEFoundation)
  6   -[DVTCoreDevice(DVTCoreDeviceIDE) supportedArchitecturesForBuildableContext:buildParameters:error:] (in IDEFoundation)
  7   _IDERunDestinationsForBuildableUsingDeviceWithBuildParameters (in IDEFoundation)
  8   -[IDERunDestinationManager runDestinationsForScheme:schemeCommands:executionEnvironment:eligibleOnly:genericOnly:architectureVisibility:] (in IDEFoundation)
  9   IDESchemeDetermineAvailableRunDestinations (in IDEFoundation)
 10   -[IDEScheme _actuallyInvalidateAvailableRunDestinations] (in IDEFoundation)
 11   addSchemeAndMakeActiveIfNecessary #1 (result:error:) in IDESwiftPackage.generateScheme(with:buildable:additionalBuildables:unsetRunnable:makeActive:orderHint:) (in IDESwiftPackageCore)
 12   IDESwiftPackage.generateScheme(with:buildable:additionalBuildables:unsetRunnable:makeActive:orderHint:) (in IDESwiftPackageCore)
 13   IDESwiftPackage.generateSchemes(_:isRootPackage:) (in IDESwiftPackageCore)
 14   IDESwiftPackage.update(from:graphHasErrors:delegate:) (in IDESwiftPackageCore)
 15   specialized IDESPMWorkspaceDelegate.rootPackagesDidUpdate(packages:graphHasErrors:modelGraphSynchronizerToken:) (in IDESwiftPackageCore)
 16   closure #1 in IDESPMWorkspaceDelegate.packageGraphDidFinishAction(_:duration:result:) (in IDESwiftPackageCore)
 17   partial apply for closure #1 in IDESPMWorkspaceDelegate.disableWorkspaceContentSynchronization(during:) (in IDESwiftPackageCore)
 18   <deduplicated_symbol> (in DVTFoundation)
 19   <deduplicated_symbol> (in DVTFoundation)
 20   thunk for @escaping @callee_guaranteed () -> () (in DVTFoundation)
 21   __58-[DVTModelObjectGraph performBlockCoalescingModelChanges:]_block_invoke (in DVTFoundation)
 22   -[DVTModelGraphTransactionScope performTransaction:] (in DVTFoundation)
 23   -[DVTModelObjectGraph performBlockCoalescingModelChanges:] (in DVTFoundation)
 24   DVTModelObjectGraph.performBlockCoalescingModelChanges<A>(_:) (in DVTFoundation)
 25   IDESPMWorkspaceDelegate.disableWorkspaceContentSynchronization(during:) (in IDESwiftPackageCore)
 26   IDESPMWorkspaceDelegate.packageGraphDidFinishAction(_:duration:result:) (in IDESwiftPackageCore)
 27   <deduplicated_symbol> (in IDESwiftPackageCore)
 28   SPMWorkspace.packageGraphActionFinished(_:) (in SwiftPM)
 29   closure #2 in closure #3 in SPMWorkspace.processPackageGraphActionsInBackgroundIfNeeded(canProcessPackageGraphActions:) (in SwiftPM)
 30   <deduplicated_symbol> (in SwiftPM)
 31   <deduplicated_symbol> (in SwiftPM)
 32   <deduplicated_symbol> (in SwiftPM)
 33   completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) (in libswift_Concurrency.dylib)


You can try to delete the /Users/omarshahine/Downloads/extensions-swift-sample-main/swift/.raycast-swift-build folder and run this command again, sometimes it helps
    Error: Build failed with 1 error:
    src/arrayArguments.tsx:3:26: ERROR: [plugin: swift-files] failed to import Swift package from 
    "/Users/omarshahine/Downloads/extensions-swift-sample-main/swift". Make sure you reference the folder that includes the 
    'Package.swift' file
omarshahine@Mac extensions-swift-sample-main %

**Comment by Visual-Studio-Coder** [comment]
For me, the issue is fixed. Maybe did you do
```bash
npx @raycast/migration@latest .
```

**Comment by omarshahine** [comment]
> npx @raycast/migration@latest

Nope. I get 1.96.3
